// Interviewer Efficiency — per-panelist interview load + feedback turnaround, from data.interviewers[]
// (interviewSchedule.list + applicationFeedback.list pipeline pass). data.panelists[] feeds the HM tab.

let ivChart = null;

const fmtTurn = (hrs) => hrs == null ? '—' : (hrs >= 24 ? (hrs / 24).toFixed(1) + 'd' : hrs.toFixed(1) + 'h');
const pct = (n, d) => d ? Math.round((n / d) * 100) : 0;

export function renderInterviewer(data) {
  const ivs = (data && data.interviewers) || [];
  const totalInterviews = (data && data.totalInterviews) || ivs.reduce((s, r) => s + (r.interviews || 0), 0);
  const totalFeedback = ivs.reduce((s, r) => s + (r.feedbackSubmitted || 0), 0);
  const turnRows = ivs.filter(r => r.avgTurnaroundHrs != null);
  const avgTurn = turnRows.length ? turnRows.reduce((s, r) => s + r.avgTurnaroundHrs, 0) / turnRows.length : null;

  if (!ivs.length) {
    return `
      <div class="section-title">Interviewer Efficiency</div>
      <p class="sub-note">Per-panelist interview load and feedback turnaround, from <code>interviewSchedule.list</code> + <code>applicationFeedback.list</code>.</p>
      <div class="card" style="text-align:center;padding:2.5rem;">
        <p style="color:var(--muted);font-size:13px;">Interviewer data is being generated by the pipeline.</p>
        <p style="color:var(--muted);font-size:11px;margin-top:6px;">It appears here after the next data refresh completes.</p>
      </div>`;
  }

  return `
    <div class="section-title">Interviewer Efficiency</div>
    <p class="sub-note">Interview load and feedback turnaround per panelist. <strong>Turnaround</strong> = time from the interview ending to feedback being submitted; <strong>completion</strong> = feedback submitted ÷ interviews.</p>

    <div class="cards" style="margin-bottom:20px">
      <div class="card"><div class="card-label">Total Interviews</div><div class="card-value">${totalInterviews.toLocaleString()}</div></div>
      <div class="card"><div class="card-label">Panelists</div><div class="card-value">${ivs.length}</div></div>
      <div class="card"><div class="card-label">Feedback Submitted</div><div class="card-value">${totalFeedback.toLocaleString()} <span style="font-size:12px;color:var(--muted)">(${pct(totalFeedback, totalInterviews)}%)</span></div></div>
      <div class="card"><div class="card-label">Avg Turnaround</div><div class="card-value">${fmtTurn(avgTurn)}</div></div>
    </div>

    <h3 class="subsection-title">Top panelists by interview load</h3>
    <div class="chart-wrap" style="max-width:820px;margin:0 auto 24px;height:${Math.max(160, Math.min(ivs.length, 15) * 24 + 40)}px;position:relative"><canvas id="ivTopChart"></canvas></div>

    <h3 class="subsection-title">All panelists</h3>
    <div class="scroll-table"><table>
      <thead><tr>
        <th style="min-width:200px">Panelist</th>
        <th>Interviews</th><th>Feedback</th><th>Pending</th><th>Completion</th><th>Avg Turnaround</th>
      </tr></thead>
      <tbody>
        ${ivs.map(r => `<tr>
          <td style="font-weight:500">${esc(r.name)}</td>
          <td>${r.interviews}</td>
          <td>${r.feedbackSubmitted}</td>
          <td>${r.pendingFeedback ? `<span style="color:var(--orange)">${r.pendingFeedback}</span>` : '0'}</td>
          <td class="${cls(pct(r.feedbackSubmitted, r.interviews))}">${pct(r.feedbackSubmitted, r.interviews)}%</td>
          <td class="${r.avgTurnaroundHrs != null && r.avgTurnaroundHrs > 72 ? 'warn' : ''}">${fmtTurn(r.avgTurnaroundHrs)}</td>
        </tr>`).join('')}
      </tbody>
    </table></div>`;
}

export function initInterviewer(data) {
  const ivs = (data && data.interviewers) || [];
  const ctx = document.getElementById('ivTopChart');
  if (!ctx || !window.Chart || !ivs.length) return;
  if (ivChart) { try { ivChart.destroy(); } catch (e) {} }
  const top = ivs.slice(0, 15);
  ivChart = new Chart(ctx, {
    type: 'bar',
    data: { labels: top.map(r => r.name), datasets: [{ label: 'Interviews', data: top.map(r => r.interviews), backgroundColor: '#4E6BA6', borderRadius: 2 }] },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } },
      scales: { x: { beginAtZero: true, grid: { color: '#f1f5f9' }, ticks: { font: { size: 10 } } }, y: { grid: { display: false }, ticks: { font: { size: 11 } } } }
    }
  });
}

function esc(s) { return String(s == null ? '' : s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c])); }
function cls(v) { return v >= 80 ? 'good' : v >= 50 ? 'pct' : v > 0 ? 'warn' : 'zero'; }
